### ISSUE TITLE
[Question] WGL: Driver does not support OpenGL version 4.3

### ISSUE THREAD

**Issue by tampro9x92** [oreonengine/Lwjgl3-Game-Engine-Programming-Series#6]
can you make it sp OpenGL 4.3 
[LWJGL] GLFW_VERSION_UNAVAILABLE error
	Description : WGL: Driver does not support OpenGL version 4.3
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1361)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1521)
		core.kernel.Window.create(Window.java:61)
		core.kernel.CoreEngine.createWindow(CoreEngine.java:41)
		core.Main.main(Main.java:9)
Exception in thread "main" java.lang.RuntimeException: Failed to create window
	at core.kernel.Window.create(Window.java:64)
	at core.kernel.CoreEngine.createWindow(CoreEngine.java:41)
	at core.Main.main(Main.java:9)

**Comment by tampro9x92** [comment]
You can fix this by going to src/core/kenel/Window.java and change "glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR,3)" to "glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR,0)"
